version: '3'

services:
  node:
    container_name: api
    build: ./node
    volumes:
      - ../:/workspace
    ports:
      - 3000:3000
    depends_on:
      - mysql
  mysql:
    container_name: db
    build:
      context: ./mysql
      args:
        - MYSQL_PORT=3306
        - MYSQL_VERSION=5.6
    volumes:
      - ~/.docker-custom/data/mysql56:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=hogar_deleite
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootP4ss
    ports:
      - "3306:3306"
    expose:
      - "3306"
