version: '3'

services:
  node:
    container_name: api
    build:
      context: .
      dockerfile: node/Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ../:/home/node/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    ports:
      - 3000:3000

    # Uncomment the next line to use a non-root user for all processes.
    user: node
    depends_on:
      - mysql
  mysql:
    container_name: db
    build:
      context: ./mysql
      args:
        - MYSQL_PORT=3306
        - MYSQL_VERSION=5.6
    volumes:
      - ~/.docker-custom/data/mysql56:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=hogar_deleite
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=rootP4ss
    ports:
      - "3306:3306"
    expose:
      - "3306"
